FROM myt/server

ARG ROOT_PASS
ENV ROOT_PASS=${ROOT_PASS}

RUN mkdir -p /mysql-template \
    && chown mysql:mysql /mysql-template

WORKDIR /workspace

RUN --mount=type=tmpfs,target=/mysql-tmpfs \
    --mount=type=bind,source=.,target=/workspace \
    chown mysql:mysql /mysql-tmpfs \
    && gosu mysql docker-init.sh
