ARG BASE_IMAGE=myt/server

FROM ${BASE_IMAGE}

ARG ROOT_PASS
ENV ROOT_PASS=${ROOT_PASS}

RUN mkdir -p /mysql-template \
    && chown mysql:mysql /mysql-template

WORKDIR /workspace

ARG MYT_COMMIT
COPY . .
RUN --mount=type=tmpfs,target=/mysql-tmpfs \
    chown mysql:mysql /mysql-tmpfs \
    && gosu mysql docker-init.sh
