FROM myvc/server

USER root

COPY \
    dump/.dump.sql  \
    dump/structure.sql  \
    myvc.config.json \
    ./
RUN gosu mysql docker-init.sh \
    && docker-dump.sh dump/structure \
    && docker-dump.sh dump/.dump \
    && gosu mysql docker-temp-stop.sh

COPY routines ./routines
COPY versions ./versions
COPY dump/fixtures.sql ./
ARG STAMP=unknown
RUN gosu mysql docker-temp-start.sh \
    && myvc-push.sh -a \
    && docker-dump.sh dump/fixtures \
    && gosu mysql docker-temp-stop.sh

RUN echo "[LOG] Import finished." \
    && rm -rf /workspace

USER mysql
