FROM myvc/server

USER root

COPY \
    myvc.config.json \
    myvc.structure.sql \
    .dump.sql \
    ./
RUN gosu mysql docker-init.sh \
    && docker-dump.sh myvc.structure \
    && docker-dump.sh .dump \
    && gosu mysql docker-temp-stop.sh

COPY routines ./routines
COPY changes ./changes
COPY myvc.fixtures.sql ./
ARG STAMP=unknown
RUN gosu mysql docker-temp-start.sh \
    && myvc-push.sh \
    && docker-dump.sh myvc.fixtures \
    && gosu mysql docker-temp-stop.sh

RUN echo "[INFO] -> Import finished" \
    && rm -rf /docker-boot

USER mysql
