FROM debian:bullseye-slim

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        mariadb-client \
        libmariadb3 \
    && rm -rf /var/lib/apt/lists/*

COPY \
    server/docker-dump.sh \
    server/docker-fixtures.sh \
    /usr/local/bin/
WORKDIR /workspace
