FROM myt/server

USER root

COPY .dump dump/.dump
COPY dump.*.sql dump/

RUN gosu mysql docker-init.sh

RUN echo "[LOG] Import finished." \
    && rm -rf /workspace

COPY fixtures.*.sql dump/

USER mysql
