FROM myt/server

USER root

COPY \
    .dump.sql  \
    beforeDump.sql \
    afterDump.sql \
    dump/

RUN gosu mysql docker-init.sh

RUN echo "[LOG] Import finished." \
    && rm -rf /workspace

USER mysql
