FROM myt/base

ENV MYSQL_ROOT_PASSWORD root

COPY docker.cnf /etc/mysql/conf.d/
COPY \
    docker-init.sh \
    docker-import.sh \
    docker-start.sh \
    /usr/local/bin/

ENTRYPOINT ["docker-start.sh"]
CMD ["mariadbd"]

HEALTHCHECK --interval=2s --timeout=10s --retries=200 \
    CMD mysqladmin ping -h 127.0.0.1 -u root --password=root || exit 1
